In [1]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

device = "cuda" if torch.cuda.is_available() else "cpu"

model_name = "gpt2"
# model_name = "gpt2-xl"
# model_name = "gpt2-large"


tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name).to(device)

2022-12-21 13:43:30.766424: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-21 13:43:30.950538: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-12-21 13:43:31.519402: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.4/lib64:/home/moonstar/.mujoco/mujoco210/bin:/usr/lib/nvidia
2022-12-21 13:43:31.519522: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinf

In [36]:
a = torch.tensor([3, 100, 5, 1, 0])
print(a)
a = torch.argsort(a, descending=True)
print(a)

tensor([  3, 100,   5,   1,   0])
tensor([1, 2, 0, 3, 4])


## Greedy search decoding 

In [42]:
import pandas as pd

input_txt = "Transformers are the"

# word to vector
input_ids = tokenizer(input_txt, return_tensors="pt")["input_ids"].to(device)

iterations = []
n_steps = 8
choices_per_step = 5

with torch.no_grad():
    for _ in range(n_steps):
        
        # dictionary
        iteration = dict()
        iteration["Input"] = tokenizer.decode(input_ids[0])

        output = model(input_ids=input_ids)
        
#         The very first embedding vectors are just the input tokens (in embedding space)
#         The very last embedding vectors are just the output logits (in embedding space)
        # select the last logit
        next_token_logits = output.logits[0, -1, :]
        
        # softmax
        next_token_probs = torch.softmax(next_token_logits, dim=-1)
        
        # torch.argsort: sort the list and return the index of a elements
        sorted_ids = torch.argsort(next_token_probs, dim=-1, descending=True)
        
        for choice_idx in range(choices_per_step):
            # token_id: candidate of the next word's embedding vector
            token_id = sorted_ids[choice_idx]
            token_prob = next_token_probs[token_id].cpu().numpy()

            token_choice = (
                f"{tokenizer.decode(token_id)} ({100 * token_prob:.2f}%)"
            )
            iteration[f"Choice {choice_idx+1}"] = token_choice
        # pick the next word that is max probability
        input_ids = torch.cat([input_ids, sorted_ids[None, 0, None]], dim=-1)
        iterations.append(iteration)
        
pd.DataFrame(iterations)

Input           Choice 1  \
0                               Transformers are the       most (9.76%)   
1                          Transformers are the most    common (22.90%)   
2                   Transformers are the most common      type (15.06%)   
3              Transformers are the most common type        of (83.13%)   
4           Transformers are the most common type of   particle (1.55%)   
5  Transformers are the most common type of particle         . (14.26%)   
6  Transformers are the most common type of parti...      They (17.48%)   
7  Transformers are the most common type of parti...       are (38.78%)   

            Choice 2            Choice 3          Choice 4  \
0       same (2.94%)        only (2.87%)      best (2.38%)   
1   powerful (6.88%)   important (6.32%)   popular (3.95%)   
2      types (3.31%)        form (1.91%)       way (1.89%)   
3         in (3.16%)           . (1.92%)         , (1.63%)   
4     object (1.02%)       light (0.71%)    energy (0.67%)   
5        in (11.57%)       that (10.19%)         , (9.57%)   
6        \n (15.19%)         The (7.06%)     These (3.09%)   
7       have (8.14%)         can (7.98%)       're (5.04%)   

               Choice 5  
0         first (1.77%)  
1      commonly (2.14%)  
2           and (1.49%)  
3           for (0.88%)  
4       objects (0.66%)  
5   accelerator (5.81%)  
6            In (3.07%)  
7       consist (1.57%)

In [43]:
input_ids = tokenizer(input_txt, return_tensors="pt")["input_ids"].to(device)
output = model.generate(input_ids, max_new_tokens=n_steps, do_sample=False)
print(tokenizer.decode(output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Transformers are the most common type of particle. They are


In [44]:
max_length = 128
input_txt = """In a shocking finding, scientist discovered \
a herd of unicorns living in a remote, previously unexplored \
valley, in the Andes Mountains. Even more surprising to the \
researchers was the fact that the unicorns spoke perfect English.\n\n
"""
input_ids = tokenizer(input_txt, return_tensors="pt")["input_ids"].to(device)
output_greedy = model.generate(input_ids, max_length=max_length, 
                               do_sample=False)
print(tokenizer.decode(output_greedy[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.


"The unicorns were very intelligent, and they were very intelligent," said Dr. David S. Siegel, a professor of anthropology at the University of California, Berkeley. "They were very intelligent, and they were very intelligent, and they were very intelligent, and they were very intelligent, and they were very intelligent, and they were very intelligent, and they were very intelligent, and they were very


## Beam search decoding 

In [5]:
import torch.nn.functional as F

def log_probs_from_logits(logits, labels):
    logp = F.log_softmax(logits, dim=-1)
    
    # logp: input
    # labels: index
    logp_label = torch.gather(logp, 2, labels.unsqueeze(2)).squeeze(-1)
    return logp_label

In [61]:
def sequence_logprob(model, labels, input_len=0):
    with torch.no_grad():
        print('##################')
        print(labels)
        output = model(labels)
        print('8888888888')
        print(output)
        print(output.logits[:, :-1, :])
        print(labels[:, 1:])
        log_probs = log_probs_from_logits(
            output.logits[:, :-1, :], labels[:, 1:])
        print('00000000000')
        print(log_probs)
        seq_log_prob = torch.sum(log_probs[:, input_len:])
    return seq_log_prob.cpu().numpy()

In [54]:
output_greedy

tensor([[  818,   257, 14702,  4917,    11, 11444,  5071,   257, 27638,   286,
         28000, 19942,  2877,   287,   257,  6569,    11,  4271, 31286,  1850,
         19272,    11,   287,   262,   843,   274, 21124,    13,  3412,   517,
          6452,   284,   262,  4837,   373,   262,  1109,   326,   262, 28000,
         19942,  5158,  2818,  3594,    13,   628,   198,     1,   464, 28000,
         19942,   547,   845, 12661,    11,   290,   484,   547,   845, 12661,
           553,   531,  1583,    13,  3271,   311,    13,   311, 28210,    11,
           257,  6240,   286, 45424,   379,   262,  2059,   286,  3442,    11,
         14727,    13,   366,  2990,   547,   845, 12661,    11,   290,   484,
           547,   845, 12661,    11,   290,   484,   547,   845, 12661,    11,
           290,   484,   547,   845, 12661,    11,   290,   484,   547,   845,
         12661,    11,   290,   484,   547,   845, 12661,    11,   290,   484,
           547,   845, 12661,    11,   290,   484,  

In [62]:
logp = sequence_logprob(model, output_greedy, input_len=len(input_ids[0]))
print(tokenizer.decode(output_greedy[0]))
print(f"\n로그 확률: {logp:.2f}")

##################
tensor([[  818,   257, 14702,  4917,    11, 11444,  5071,   257, 27638,   286,
         28000, 19942,  2877,   287,   257,  6569,    11,  4271, 31286,  1850,
         19272,    11,   287,   262,   843,   274, 21124,    13,  3412,   517,
          6452,   284,   262,  4837,   373,   262,  1109,   326,   262, 28000,
         19942,  5158,  2818,  3594,    13,   628,   198,     1,   464, 28000,
         19942,   547,   845, 12661,    11,   290,   484,   547,   845, 12661,
           553,   531,  1583,    13,  3271,   311,    13,   311, 28210,    11,
           257,  6240,   286, 45424,   379,   262,  2059,   286,  3442,    11,
         14727,    13,   366,  2990,   547,   845, 12661,    11,   290,   484,
           547,   845, 12661,    11,   290,   484,   547,   845, 12661,    11,
           290,   484,   547,   845, 12661,    11,   290,   484,   547,   845,
         12661,    11,   290,   484,   547,   845, 12661,    11,   290,   484,
           547,   845, 12661,    

In [53]:
output_beam = model.generate(input_ids, max_length=max_length, num_beams=15, 
                             do_sample=False)
logp = sequence_logprob(model, output_beam, input_len=len(input_ids[0]))
print(tokenizer.decode(output_beam[0]))
print(f"\n로그 확률: {logp:.2f}")

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.


The study, published in the journal Proceedings of the National Academy of Sciences, is the first to show that unicorns are able to communicate with one another.


"This is the first study to show that unicorns are able to communicate with one another," said study co-author Dr. Michael Siegel, a professor of biology at the University of California, San Diego. "This is the first

로그 확률: -75.20


In [9]:
output_beam = model.generate(input_ids, max_length=max_length, num_beams=5, 
                             do_sample=False, no_repeat_ngram_size=2)
logp = sequence_logprob(model, output_beam, input_len=len(input_ids[0]))
print(tokenizer.decode(output_beam[0]))
print(f"\n로그 확률: {logp:.2f}")

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.


The researchers, from the University of California, San Diego, and the National Science Foundation (NSF) in Boulder, Colorado, were able to translate the words of the unicorn into English, which they then translated into Spanish.

"This is the first time that we have translated a language into an English language," said study co-author and NSF professor of linguistics and evolutionary biology Dr.

로그 확률: -101.88
